### ISSUE TITLE
More robust selector heuristics - GitHub READMEs example

### ISSUE THREAD

**Issue by dandv** [fczbkk/css-selector-generator#6] opened 2015-09-10 10:45 UTC
Say we wanted a selector for the "How to use" heading in the README of this project. Currently the returned selector is `article > :nth-child(5)`.

That heading though has as a first element a link with a unique id. This `<hX><a id="...">` pattern is pretty common, and an `h2 + #...` selector would be more robust for that case.

Any thoughts on extending the library with a mechanism to take such heuristics into consideration?

**Comment by fczbkk** [comment] 2015-09-10 11:35
@dandv Can you please provide me with a snippet of HTML which produces this selector?

If there is an `id` attribute, the library should use it. The other two cases when it will not use are:

- ID is not unique (thus invalid)
- ID selectors are disabled via the options

**Comment by dandv** [comment] 2015-09-10 11:47
The HTML is at https://github.com/fczbkk/css-selector-generator#how-to-use:

```html
<h2><a id="user-content-how-to-use" class="anchor" href="#how-to-use" aria-hidden="true"><span class="octicon octicon-link"></span></a>How to use</h2>
```

The selector generator behaves correctly; I was wondering if there was room for improvement with heuristics such as "If the element is followed by another element with an id, return a selector like `elem1 + #elem2`".

**Comment by robinpokorny** [comment] 2015-09-10 13:02
@dandv CSS does not have a selector to test presence of children elements, sometimes this is called parent selector. It was proposed a few times, although.

For example jQuery has it implemented as `:has()` pseudoclass.

**Comment by robinpokorny** [comment] 2015-09-10 13:04
In addition, any selector of the form `h2 + #...` is overqualified, as ID's must be unique.

**Comment by robinpokorny** [comment] 2015-09-10 13:10
@dandv I see where the misunderstanding could happen.

You wrote: „If the element is followed by another element with an id, return a selector like elem1 + #elem2“

But `+`, a.k.a. [adjacent sibling selector](https://developer.mozilla.org/en-US/docs/Web/CSS/Adjacent_sibling_selectors), works exactly opposite: „It will select only the specified element that immediately follows the former specified element.“

**Comment by fczbkk** [comment] 2015-09-10 14:59
@dandv I have created a fiddle that creates a CSS selector for all elements in your sample: https://jsfiddle.net/fczbkk/4bpqce2y/1/

The selectors seem to be fine. Please, feel free to update the fiddle to simulate your problem.

**Comment by fczbkk** [comment] 2015-09-20 15:33
@dandv Can I close this, or is this still an issue for you? If it is still issue, can you please provide me with a way to replicate the problem?

**Comment by fczbkk** [comment] 2015-10-24 07:16
Closing due to inactivity. Feel free to reopen this with instructions on how to reproduce the issue.

**Closed by fczbkk** 2015-10-24 07:16 UTC

**Comment by dandv** [comment] 2015-10-24 08:53
> But +, a.k.a. adjacent sibling selector, works exactly opposite

Correct. This particular issue should stay closed, and I'll see if other examples where smarter selector logic can help will come up.
