### ISSUE TITLE
Cannot read property 'querySelectorAll' of null

### ISSUE THREAD

**Issue by webpolis** [fczbkk/css-selector-generator#41] opened 2020-07-02 15:54 UTC
Using v2.1.1, _Cannot read property 'querySelectorAll' of null_ is thrown on some elements when clicking.

Go to https://es.wikipedia.org/wiki/Biopel%C3%ADcula and click on any of the pictures at the middle of the page on the right. And then on the X (Close) button at top right.

Related to https://github.com/fczbkk/css-selector-generator/issues/19

**Comment by webpolis** [comment] 2020-07-02 16:12
Well, I think this has to do with the element being removed right away from the DOM tree on click.

This might help others: when catching events, it worth using the **useCapture** boolean flag in https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener

**Comment by fczbkk** [comment] 2020-07-08 06:07
@webpolis Thanks for the report.

I have created `v2.1.2` which should contain a fix for this edge scenario. Attempts to get a selector on parent-less element (this can happen e.g. when element is removed from DOM) should not cause a crash.

I have tested in on the Wikipedia page you linked, I was able to reproduce the problem and it seems to be working after the fix.

**Closed by fczbkk** 2020-07-08 06:07 UTC
Labels: bug
